### ISSUE TITLE
ServerBuilder/ClientBuilder for nested namespaces/packages

### ISSUE THREAD

**Issue by nethack42** [kondi/rxjs-grpc#14]
Hello,

I've got some protobuf service definitions with nested namespaces/package names.

```protobuf
syntax = "proto3";

package foo.bar;

service Dummy {
    rpc Echo(EchoMessage) returns (EchoMessage) {}
}

message EchoMessage {
    string payload = 1;
}
```

Unfortunately the serverBuilder failes to create the server as I cannot pass the correct package name. The generated TypeScript code has the following structure: 

```typescript
export namespace foo {
      export interface ServerBuilder {}

      // ...

     export namespace bar {
          export interface Echo {
                 // ....
          }

          export interface ServerBuilder {
              addEcho(echo: Echo): void;
          }
     }
}
```

I assume that I need to pass "foo.bar" as the package name to serverBuilder() like below:

```
const server = serverBuilder<foo.bar.ServerBuilder>('dummy.proto', 'foo.bar');
```

Using "foo.bar" fails at `grpc.load(XXX)[pkgName]`.

Did I make a mistake or are nested packages/namespaces not yet supported by rxjs-grpc?

Best regards
Patrick

**Comment by kondi** [comment]
Thanks for the report.
It should be fixed in version 0.1.4.
