### ISSUE TITLE
Unable to run example with TypeScript 2.5.x

### ISSUE THREAD

**Issue by alex-dixon** [kondi/rxjs-grpc#16]
Upstream issue https://github.com/Microsoft/TypeScript/issues/18301

`npm install -g typescript@latest` solved this for me in combination with running `tsc` in examples folder then running `node client.js` and `node server.js` to avoid using `ts-node`.

Worked with tsc Version 2.6.0-dev.20170919.

Not sure what version I had before (sorry oops) but judging by the issue seems the fix will land in 2.6.0.

**Comment by kondi** [comment]
It is already fixed in the TypeScript 2.5 branch by https://github.com/Microsoft/TypeScript/pull/18360, but not released yet.
I suggest to use TypeScript 2.4.x temporarily until 2.5.3 is released.

**Comment by FedeBev** [comment]
Look if PR #35 solve your issue!

**Comment by kondi** [comment]
Typescript v2.5.3 has been released, it should work, although I haven't checked. But it is working with v2.8.4 and v3.0.3.
