### ISSUE TITLE
Usage without RxJS? (Pure gRPC to TypeScript)

### ISSUE THREAD

**Issue by quicksnap** [kondi/rxjs-grpc#21]
I'm just getting into gRPC so forgive any ignorance =) I'd like to have gRPC output static codegen for TypeScript, but there's nothing on the horizon: https://github.com/grpc/grpc/issues/6630

However, it seems this project leverages `protobufjs` pretty well to annotate the RxJS-based api surface; could we refactor some of it to expose a non-RxJS interface akin to what the  [official examples](https://github.com/grpc/grpc/tree/master/examples/node/static_codegen) show? 

Again, I'm just digging into gRPC and protobuf, so I'm not keen on all the nuances. I'd be happy to help once I'm more familiar with the lay of the land.

**Comment by quicksnap** [comment]
Perhaps it's better just to directly use `protobufjs` directly for the message codegen and use the inferred typing from what gRPC generates. Types for the server methods are inferred pretty decently. /shrug

**Comment by adematte** [comment]
@quicksnap it's actually pretty easy to write your own protoc plugin to control the generated code and make it more suitable to your coding style/requirements. 

Apart from this project (I love the observable approach with grpc), you can also take inspiration from these repos: 
https://github.com/improbable-eng/ts-protoc-gen
https://github.com/agreatfool/grpc_tools_node_protoc_ts

**Comment by kondi** [comment]
@quicksnap Do you think this is still relevant?

**Comment by quicksnap** [comment]
My current job doesn't involve any gRPC, so if you want to close it, I'm totally fine with that! =)
