### ISSUE TITLE
Don't work in Angular

### ISSUE THREAD

**Issue by eugenotop** [kondi/rxjs-grpc#38]
$ ng serve

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 10% building 3/3 modules 0 active[HPM] Proxy created: /api  ->  http://localhost:3000
                                                                                          
Date: 2019-06-11T22:48:57.730Z
Hash: c29506e37eae8eb873f3
Time: 18016ms
chunk {main} main.js, main.js.map (main) 42.7 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 149 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 17.4 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.22 MB [initial] [rendered]

WARNING in pnode_modules/grpc/src/grpc_extension.js 32:12-33
Critical dependency: the request of a dependency is an expression

WARNING in project/node_modules/grpc/node_modules/node-pre-gyp/lib/pre-binding.js 20:22-48
Critical dependency: the request of a dependency is an expression

WARNING in project/node_modules/grpc/node_modules/node-pre-gyp/lib/util/versioning.js 17:20-67
Critical dependency: the request of a dependency is an expression

WARNING in project/node_modules/grpc/node_modules/minimatch/minimatch.js
Module not found: Error: Can't resolve 'path' in 'project/node_modules/grpc/node_modules/minimatch'

ERROR in project/node_modules/grpc/node_modules/detect-libc/lib/detect-libc.js
Module not found: Error: Can't resolve 'child_process' in 'project/node_modules/grpc/node_modules/detect-libc/lib'
ERROR in project/node_modules/grpc/index.js
Module not found: Error: Can't resolve 'fs' in 'project/node_modules/grpc'
ERROR in project/node_modules/grpc/node_modules/detect-libc/lib/detect-libc.js
Module not found: Error: Can't resolve 'fs' in 'project/node_modules/grpc/node_modules/detect-libc/lib'
ERROR in project/node_modules/grpc/node_modules/fs.realpath/index.js
Module not found: Error: Can't resolve 'fs' in 'project/node_modules/grpc/node_modules/fs.realpath'
ERROR in project/node_modules/grpc/node_modules/fs.realpath/old.js
Module not found: Error: Can't resolve 'fs' in 'project/node_modules/grpc/node_modules/fs.realpath'
ERROR in project/node_modules/grpc/node_modules/node-pre-gyp/lib/pre-binding.js
Module not found: Error: Can't resolve 'fs' in 'project/node_modules/grpc/node_modules/node-pre-gyp/lib'
ERROR in project/node_modules/grpc/node_modules/node-pre-gyp/lib/util/napi.js
Module not found: Error: Can't resolve 'fs' in 'project/node_modules/grpc/node_modules/node-pre-gyp/lib/util'
ERROR in project/node_modules/grpc/node_modules/rimraf/rimraf.js
Module not found: Error: Can't resolve 'fs' in 'project/node_modules/grpc/node_modules/rimraf'
ERROR in project/node_modules/grpc/node_modules/rimraf/node_modules/glob/sync.js
Module not found: Error: Can't resolve 'fs' in 'project/node_modules/grpc/node_modules/rimraf/node_modules/glob'
ERROR in project/node_modules/grpc/node_modules/rimraf/node_modules/glob/glob.js
Module not found: Error: Can't resolve 'fs' in 'project/node_modules/grpc/node_modules/rimraf/node_modules/glob'
ERROR in project/node_modules/grpc/src/grpc_extension.js
Module not found: Error: Can't resolve 'fs' in 'project/node_modules/grpc/src'
ERROR in project/node_modules/rxjs-grpc/node_modules/@grpc/proto-loader/build/src/index.js
Module not found: Error: Can't resolve 'fs' in 'project/node_modules/rxjs-grpc/node_modules/@grpc/proto-loader/build/src'
ERROR in project/node_modules/grpc/node_modules/detect-libc/lib/detect-libc.js
Module not found: Error: Can't resolve 'os' in 'project/node_modules/grpc/node_modules/detect-libc/lib'
ERROR in project/node_modules/grpc/node_modules/has-unicode/index.js
Module not found: Error: Can't resolve 'os' in 'project/node_modules/grpc/node_modules/has-unicode'
ERROR in project/node_modules/grpc/index.js
Module not found: Error: Can't resolve 'path' in 'project/node_modules/grpc'[22m
ERROR in project/node_modules/grpc/node_modules/fs.realpath/old.js
Module not found: Error: Can't resolve 'path' in 'project/node_modules/grpc/node_modules/fs.realpath'
ERROR in project/node_modules/grpc/node_modules/node-pre-gyp/lib/pre-binding.js
Module not found: Error: Can't resolve 'path' in 'project/node_modules/grpc/node_modules/node-pre-gyp/lib'
ERROR in project/node_modules/grpc/node_modules/node-pre-gyp/lib/util/versioning.js
Module not found: Error: Can't resolve 'path' in 'project/node_modules/grpc/node_modules/node-pre-gyp/lib/util'
ERROR in project/node_modules/grpc/node_modules/rimraf/rimraf.js
Module not found: Error: Can't resolve 'path' in 'project/node_modules/grpc/node_modules/rimraf'
ERROR in project/node_modules/grpc/node_modules/rimraf/node_modules/glob/glob.js
Module not found: Error: Can't resolve 'path' in 'project/node_modules/grpc/node_modules/rimraf/node_modules/glob'
ERROR in project/node_modules/grpc/node_modules/rimraf/node_modules/glob/sync.js
Module not found: Error: Can't resolve 'path' in 'project/node_modules/grpc/node_modules/rimraf/node_modules/glob'
ERROR in project/node_modules/grpc/node_modules/rimraf/node_modules/glob/common.js
Module not found: Error: Can't resolve 'path' in 'project/node_modules/grpc/node_modules/rimraf/node_modules/glob'
ERROR in project/node_modules/grpc/src/grpc_extension.js
Module not found: Error: Can't resolve 'path' in 'project/node_modules/grpc/src'
ERROR in project/node_modules/rxjs-grpc/node_modules/@grpc/proto-loader/build/src/index.js
Module not found: Error: Can't resolve 'path' in 'project/node_modules/rxjs-grpc/node_modules/@grpc/proto-loader/build/src'
ERROR in project/node_modules/grpc/src/client.js
Module not found: Error: Can't resolve 'stream' in 'project/node_modules/grpc/src'
ERROR in project/node_modules/grpc/src/server.js
Module not found: Error: Can't resolve 'stream' in 'project/node_modules/grpc/src'
ℹ ｢wdm｣: Failed to compile.
^C

**Comment by kondi** [comment]
Hello!
Sorry, but the grpc module is not supported in browser, see https://github.com/kondi/rxjs-grpc/issues/5
