### ISSUE TITLE
Update README example

### ISSUE THREAD

**Issue by JustGreg** [kondi/rxjs-grpc#6]
first of all I would like to say thank you for this great piece of work.

The server code on the README wouldn't work because `addGreeter` returns a `sample.ServerBuilder`, which does not include the `GenericServerBuilder` (= no `start` function).

Therefore it's not possible to write the server-config in a chain. it should look like the helloworld-example.

```typescript
type ServerBuilder = sample.ServerBuilder;
// Pass the path of proto file and the name of namespace
const server = serverBuilder<ServerBuilder>('sample.proto', 'sample');
// Add implementation
server.addGreeter({
  sayHello(request: sample.HelloReply) {
    return Observable.of({
      message: 'Hello ' + request.name
    });
  }
});
// Start the server to listen on port 50051
server.start('0.0.0.0:50051');
```

**Comment by kondi** [comment]
Thanks, nice finding, was changed by 7f7ebf3. It is good to know someone have tried it :)
